wandb_version: 1

epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 16
pos_neg_ratio:
  desc: null
  value: 3
dataset:
  desc: null
  value: earthquakes
matching_solution:
  desc: null
  value: deep_matcher
run:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683012305.429198
    t:
      1:
      - 55
      2:
      - 1
      - 5
      - 40
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.16
      5: 0.15.0
      8:
      - 5
    framework: torch
