wandb_version: 1

run_id:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 20
n_epochs:
  desc: null
  value: 15
lr:
  desc: null
  value: 3.0e-05
max_len:
  desc: null
  value: 256
lm:
  desc: null
  value: roberta
fp16:
  desc: null
  value: 'True'
dataset:
  desc: null
  value: earthquakes
matching_solution:
  desc: null
  value: ditto
run:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.7.7
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.9.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682890238.32918
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.7.7
      5: 0.15.0
      6: 4.9.2
      8:
      - 5
